### ISSUE TITLE
Couleurs trop foncées

### ISSUE THREAD

**Issue by czerwinski76** [CamillzScript/jvc-cleaner-script#1]
@CamillzScript Pouvez vous revenir à des couleurs verte et rouge plus claires comme dans les anciennes version svp ?
C'est trop foncé pour y voir le contenu des messages écrit en noir.

Depuis que les couleurs ont changées je suis obligé de mettre le texte en surbrillance pour pouvoir le lire facilement.
Merci.

**Comment by CamillzScript** [comment]
Vous devez utilisé un autre plugin qui fait bouger le site, je n'est pas touché au couleur depuis plus d'un ans.
De plus je viens de faire une grosse mise à jours du script en pensent que ce bug venez de mon script mais non.
Vous avez une image à me montrer pour mieux expliquer le bug que vous rencontré ainsi que la liste des script actif sur jvc. Je pouvez peut être faire quelques modifications pour le rendre compatible avec les autre script que vous utilisez.

**Comment by czerwinski76** [comment]
Merci de m'avoir répondu.
Sur JV j'utilise que votre script.

Avant j'avais votre ancien script "jcv-top-comment".

![21-08-2023_054548](https://github.com/CamillzScript/jvc-cleaner-script/assets/19463267/e5aef62c-c803-4c92-975a-537a0cd7aa5d)
![21-08-2023_055948](https://github.com/CamillzScript/jvc-cleaner-script/assets/19463267/a9e5a79e-a49e-44e7-b92b-00cae74d6b91)
![21-08-2023_055925](https://github.com/CamillzScript/jvc-cleaner-script/assets/19463267/d85a238c-cd88-4711-80f0-934a170770c6)
![21-08-2023_060002](https://github.com/CamillzScript/jvc-cleaner-script/assets/19463267/6552ef92-a7b7-4958-9175-036c63583289)
![21-08-2023_055938](https://github.com/CamillzScript/jvc-cleaner-script/assets/19463267/30c4fb20-bba3-4c68-8067-c9b47e74a883)

---------------------------------------------------------------------------

Les couleurs avec jcv-top-comment :

![jv top comment](https://github.com/CamillzScript/jvc-cleaner-script/assets/19463267/e6925663-15d0-4e1c-87a4-5959f3f57e9a)

**Comment by CamillzScript** [comment]
C'est parce que je n'utilise que la version "dark" du site, je modifie sa dans l'heure.

**Comment by czerwinski76** [comment]
Merci [CamillzScript](https://github.com/CamillzScript).
C'est bien agréable de votre part !

**Comment by CamillzScript** [comment]
C'est fait, j'ai aussi réparer le bug d'affichage sur le thème clair sur la page d'accueil.
Avec le thème clair les message positif et négatif sont plus clair et pour le thème sombre les commentaires reste de la mêmes couleur mêmes.

Suivre ce liens pour faire la mise à jours : https://jvccleanerscript.web-freelance.paris
